language: php

os:
  - linux
  - osx

php:
  - 5.4
  - 5.5
  - 5.6
before_install:
  - pip install --user codecov
before_script:
  - ./bin/post-update.sh
after_success:
  - codecov
script:
  - ./bin/pre-commit.sh
  - ./bin/post-commit.sh
